@startuml kind_of_ai
skinparam backgroundColor transparent
人工知能 <|-- ルールベース制御 
人工知能 <|-- 機械学習
機械学習 <|-- 遺伝的アルゴリズム
機械学習 <|-- サポートベクターマシン
機械学習 <|-- ニューラルネットワーク
ニューラルネットワーク <|-- パーセプトロン
ニューラルネットワーク <|-- 深層学習
深層学習<|-- CNN
深層学習<|-- RNN
@enduml
